# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pid.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1140, 828)
        self.ventValveButton = QtGui.QPushButton(Dialog)
        self.ventValveButton.setGeometry(QtCore.QRect(740, 280, 31, 31))
        self.ventValveButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ventValveButton.setStyleSheet(_fromUtf8("border: none;"))
        self.ventValveButton.setText(_fromUtf8(""))
        self.ventValveButton.setCheckable(True)
        self.ventValveButton.setChecked(False)
        self.ventValveButton.setDefault(True)
        self.ventValveButton.setObjectName(_fromUtf8("ventValveButton"))
        self.mainValveButton = QtGui.QPushButton(Dialog)
        self.mainValveButton.setGeometry(QtCore.QRect(923, 437, 41, 27))
        self.mainValveButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mainValveButton.setStyleSheet(_fromUtf8("border: none;"))
        self.mainValveButton.setText(_fromUtf8(""))
        self.mainValveButton.setCheckable(True)
        self.mainValveButton.setChecked(False)
        self.mainValveButton.setDefault(False)
        self.mainValveButton.setObjectName(_fromUtf8("mainValveButton"))
        self.eStopButton = QtGui.QPushButton(Dialog)
        self.eStopButton.setGeometry(QtCore.QRect(625, 116, 41, 27))
        self.eStopButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.eStopButton.setStyleSheet(_fromUtf8("border: none;"))
        self.eStopButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("closed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eStopButton.setIcon(icon)
        self.eStopButton.setCheckable(False)
        self.eStopButton.setChecked(False)
        self.eStopButton.setObjectName(_fromUtf8("eStopButton"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(940, 360, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.flowMeterLCD = QtGui.QLCDNumber(Dialog)
        self.flowMeterLCD.setGeometry(QtCore.QRect(783, 382, 91, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.flowMeterLCD.setFont(font)
        self.flowMeterLCD.setStyleSheet(_fromUtf8(""))
        self.flowMeterLCD.setFrameShadow(QtGui.QFrame.Raised)
        self.flowMeterLCD.setLineWidth(0)
        self.flowMeterLCD.setDigitCount(4)
        self.flowMeterLCD.setMode(QtGui.QLCDNumber.Dec)
        self.flowMeterLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.flowMeterLCD.setObjectName(_fromUtf8("flowMeterLCD"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(800, 370, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(620, 200, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(520, 120, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(910, 460, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(420, 120, 66, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.logButton = QtGui.QPushButton(Dialog)
        self.logButton.setGeometry(QtCore.QRect(475, 116, 31, 27))
        self.logButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.logButton.setStyleSheet(_fromUtf8("border: none;"))
        self.logButton.setText(_fromUtf8(""))
        self.logButton.setCheckable(True)
        self.logButton.setDefault(True)
        self.logButton.setObjectName(_fromUtf8("logButton"))
        self.background = QtGui.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(400, 110, 691, 391))
        self.background.setText(_fromUtf8(""))
        self.background.setPixmap(QtGui.QPixmap(_fromUtf8("P_ID.jpg")))
        self.background.setObjectName(_fromUtf8("background"))
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 361, 551))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalPlots = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalPlots.setMargin(0)
        self.verticalPlots.setObjectName(_fromUtf8("verticalPlots"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(720, 303, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tankPressureLCD = QtGui.QLCDNumber(Dialog)
        self.tankPressureLCD.setGeometry(QtCore.QRect(620, 220, 91, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tankPressureLCD.setFont(font)
        self.tankPressureLCD.setStyleSheet(_fromUtf8(""))
        self.tankPressureLCD.setFrameShadow(QtGui.QFrame.Raised)
        self.tankPressureLCD.setLineWidth(0)
        self.tankPressureLCD.setDigitCount(4)
        self.tankPressureLCD.setMode(QtGui.QLCDNumber.Dec)
        self.tankPressureLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.tankPressureLCD.setObjectName(_fromUtf8("tankPressureLCD"))
        self.outletPressureLCD = QtGui.QLCDNumber(Dialog)
        self.outletPressureLCD.setGeometry(QtCore.QRect(970, 370, 91, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.outletPressureLCD.setFont(font)
        self.outletPressureLCD.setStyleSheet(_fromUtf8(""))
        self.outletPressureLCD.setFrameShadow(QtGui.QFrame.Raised)
        self.outletPressureLCD.setLineWidth(0)
        self.outletPressureLCD.setDigitCount(4)
        self.outletPressureLCD.setMode(QtGui.QLCDNumber.Dec)
        self.outletPressureLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.outletPressureLCD.setObjectName(_fromUtf8("outletPressureLCD"))
        self.background.raise_()
        self.ventValveButton.raise_()
        self.mainValveButton.raise_()
        self.eStopButton.raise_()
        self.label.raise_()
        self.flowMeterLCD.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.logButton.raise_()
        self.verticalLayoutWidget.raise_()
        self.label_8.raise_()
        self.tankPressureLCD.raise_()
        self.outletPressureLCD.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Outlet Pressure", None))
        self.label_2.setText(_translate("Dialog", "Flow Rate", None))
        self.label_3.setText(_translate("Dialog", "Tank Pressure", None))
        self.label_5.setText(_translate("Dialog", "Emergency Stop", None))
        self.label_6.setText(_translate("Dialog", "Main Valve", None))
        self.label_7.setText(_translate("Dialog", "Log Data", None))
        self.label_8.setText(_translate("Dialog", "Vent Valve", None))

